server:
  port: 7000
spring:
  application:
    name: eureka-server
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://server2:7009/eureka/
  instance:
    hostname: server1