server:
  port: 7002
spring:
  application:
    name: eureka-consumer
eureka:
  client:
    service-url:
      defaultZone: http://server1:7000/eureka/,http://server2:7009/eureka/
  instance:
    hostname: localhost